name: task-engine
services:
  go:
    container_name: go
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - private_network
    
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DB}
    networks:
      - private_network

  redis:
    container_name: redis
    image: redis 
    ports:
      - "6379:6379"
    networks:
      - private_network
  
networks:
  private_network:
    driver: bridge


  
    
    